### ISSUE TITLE
hi where is the secret chamber?

### ISSUE THREAD

**Issue by rimumba** [tdauth/wowr#812] opened 2022-04-29 07:22 UTC
I've been playing version 1.4 and it says somewhere the secret chamber will be revealed lvl 40.. well it didnt reveal

**Comment by tdauth** [comment] 2022-04-29 09:27
The secret chamber is the bonus hero selection.
Not sure why you are playing an old version like this.
In 2.0 it says that you get bonus heroes at level 40. It used to be called secret hero chamber.

**Comment by rimumba** [comment] 2022-04-29 11:12
oh as in which area is the secret hero chamber? 

so the latest version is 2.0? i cant find the download link in epicwar

**Comment by tdauth** [comment] 2022-04-29 14:25
You can see all version here in the repository: https://github.com/tdauth/wowr
The official downlad is here: https://www.hiveworkshop.com/threads/world-of-warcraft-reforged-2-0.304616/
The area with the bonus heroes is called "Secret Hero Chamber".

**Comment by tdauth** [comment] 2022-04-30 15:17
Since this is not a bug but just a question I will close it. Please ask stuff like this on Discord: https://discord.gg/eM34z36
or Hive.

**Closed by tdauth** 2022-04-30 15:17 UTC
